jobs:
  include:
    - stage: Build/Test
      name: Compile C++
      language: C++
      compiler: gcc
      install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install -y gcc-snapshot
        - sudo apt-get install -y gcc-6 g++-6
      before_script:
        - CXX=g++-6
      script:
        - make
        - ./bin/test_mbs_analytics
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - ./bin/mbs_analytics.*
          - ./bin/test_mbs_analytics.*
    - stage: Build/Test
      name: Compile C#
      language: csharp
      dotnet: 2.2.401
      mono: none
      before_install:
        - cd ./src/frontend
      script:
        - dotnet build
