matrix:
  include:
    - language: C++
      compiler: gcc
      addons:
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install -y gcc-snapshot
        - sudo apt-get install -y gcc-6 g++-6
      install:
        - CXX=g++-6
      script: make
    - language: csharp
      dotnet: 2.2.401
      mono: none
      before_install:
        - cd ./src/frontend
      script:
        - dotnet build
