jobs:
  include:
    - stage: Build/Test
      name: Compile C++ and Run Tests
      language: C++
      compiler: gcc
      install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install -y gcc-snapshot
        - sudo apt-get install -y gcc-6 g++-6
      before_script:
        - CXX=g++-6
      script:
        - make
        - ./bin/test_mbs_analytics
      # before_deploy:
      #   - echo "Running before_deploy"
      #   - git config --local user.name "Travis CI"
      #   - git config --local user.email "build@travis-ci.com"
      #   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      #   - git tag $TRAVIS_TAG
      #   - git push https://$GITHUB_TOKEN@github.com/gandhis1/mbs-analytics --tags
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - ./bin/mbs_analytics.*
        # on:
        #   tags: true
    - stage: Build/Test
      name: Compile C#
      language: csharp
      dotnet: 2.2.401
      mono: none
      before_install:
        - cd ./src/frontend
      script:
        - dotnet build
