jobs:
  include:
    - stage: Build/Test
      name: Compile C++ and Run Tests
      language: c++
      compiler: clang
      install:
        - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt update
        - sudo apt install clang
        - sudo apt install libstdc++-8-dev
      script:
        - make -C ./src/engine
        - make -C ./test/engine
        - ./bin/test_mbs_analytics
      before_deploy:
        - echo "Running before_deploy"
        - git config --local user.name "Travis CI"
        - git config --local user.email "build@travis-ci.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
        - git push https://$GITHUB_TOKEN@github.com/gandhis1/mbs-analytics --tags
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - ./bin/mbs_analytics.*
        on:
          tags: true
    - stage: Build/Test
      name: Compile C#
      language: csharp
      dotnet: 3.0.100
      mono: none
      before_install:
        - cd ./src/frontend
      script:
        - dotnet build
